version: '3'

services:
  backend:
    build: 
      context: ./server
    container_name: server
    working_dir: /app
    ports:
      - "42069:42069"
      

  frontend:
    build: 
      context: ./Client
    working_dir: /app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend

