import instance from '@/Helpers/Config/axios.config';
import DeleteIcon from '@mui/icons-material/Delete'
import Script from 'next/script';
import { useEffect, useState } from 'react';

export default function CartPage({ cartData, changeQunty, remove_product }) {
    let [tokens, settoken] = useState()
    function checkout(){
        instance.get("/user/cart/checkout").then((response) => {
        settoken(response.data.data);
    })
    }
    useEffect(()=>{
        checkout()
    },[])

    
    const createCardOrder = async () => {
        var options = {
            "key": "rzp_test_bQuC3tCBEV6iGn",
            "amount":"300",//token.amount
            "currency": "INR",
            "name": "Nova ",
            "image": "https://img.freepik.com/premium-vector/initial-g-residential-real-estate-symbol-logo-design_284881-411.jpg?w=2000",
            "order_id": "order_MzeXYVwH7HnevA",   ///token.id  //This is generated by razorpay on creating an order using instance.order.create
            "handler": function (response) {
                alert(response.razorpay_payment_id);
                alert(response.razorpay_order_id);
                alert(response.razorpay_signature)
            },
            "prefill": { //We recommend using the prefill parameter to auto-fill customer's contact information, especially their phone number
                "name": "Gaurav Kumar", //your customer's name
                "email": "gaurav.kumar@example.com",
                "contact": "9000090000"  //Provide the customer's phone number for better conversion rates 
            },

            "theme": { "color": "#d90429" }
        }; 

        var rzp1 = new Razorpay(options);
          rzp1.open()
    }

        const call = () => {
            createCardOrder();
        };
        
    return (
        <>
                  <Script src='https://checkout.razorpay.com/v1/checkout.js' />
        <section>
  


            <div class="ProductDetails" style={{ width: '70.5rem' }}>

                <table style={{ width: '70rem', marginRight: '20rem' }}>

                    <tr>
                        <th>Items</th>
                        <th></th>
                        <th>Quantity</th>
                        <th>Remove</th>
                    </tr>
                    {
                        cartData &&
                        Object.keys(cartData).includes('products' )&&
                        cartData.products.map(({ productdetails, quntity }) => {
                            return (
                                <>
                                    <tr key={productdetails._id} style={{ height: '6rem' }}>
                                        <td><img style={{ marginTop: '0.2rem' }} src="https://imgur.com/3Y1DLYC.png"
                                            alt="" /></td>
                                        <td>{productdetails.prodName}</td>
                                        <td>
                                            <div class="pcount">
                                                <div><button onClick={() => changeQunty(productdetails._id, 1)} style={{ backgroundColor: 'rgb(25,118,210)', padding: '0.3rem', width: '1.7rem', height: '1.5rem', display: 'flex', alignItems: 'center ', justifyContent: 'center', borderRadius: '0.rem' }} >+</button></div>
                                                <div><span style={{ fontWeight: 500, color: 'black', padding: '0.8rem', paddingTop: '0.4rem', paddingBottom: '0.4rem', fontFamily: 'Poppins' }}>{quntity}</span></div>
                                                <div><button onClick={() => changeQunty(productdetails._id, -1)} style={{ backgroundColor: 'rgb(25,118,210)', padding: '0.3rem', width: '1.7rem', height: '1.5rem', display: 'flex', alignItems: 'center ', justifyContent: 'center', borderRadius: '0.rem' }}>-</button></div>
                                            </div>
                                        </td>
                                        <td><button style={{ border: 'none', outline: 'none', }} onClick={() => remove_product(productdetails._id)}><DeleteIcon style={{ transform: 'scale(2.3)', fontSize: '12px', color: 'rgb(228, 79, 79)' }} /></button></td>
                                    </tr>
                                </>
                            )
                        })
                    }
                </table>
            </div>
            <div class="CardAndCheckout">
                <p>ORDER SUMMARY</p>
                <p>ITEMS: <span>{cartData && Object.keys(cartData).includes('products' )&& cartData.products.length}</span></p>  <p>PROMO CODE:</p>
                <input type="text" placeholder="AAA-BBB-YYY-CCC" />
                <div class="checkbtn">

                    <button class="apply">APPLY</button>
                </div>
                {
                    cartData &&
                    <div class="subtotal">
                        <div>TOTAL COST :</div> <span>$ {cartData.totalPriceInCart}</span>
                    </div>
                }
                <div><button class="checkout" onClick={()=>call()} >Buy Now</button></div>

            </div>
        </section >
</>
     )
 }
       

